### ISSUE TITLE
FileNotFoundError while using default

### ISSUE THREAD

**Issue by jackievaleri** [Bonidia/BioAutoML#2]
Hello! Thank you for all your previous help. I am hitting a FileNotFound error when I run the example below. Hoping you can advise on this - the test_directory/ does not exist before running this code so I am unsure how to satisfy this error. Thanks again for your help! -Jackie

`python BioAutoML/BioAutoML-feature.py -fasta_train BioAutoML/Case\ Studies/CS-I-A/E_coli/train/rRNA.fasta BioAutoML/Case\ Studies/CS-I-A/E_coli/train/sRNA.fasta -fasta_label_train rRNA sRNA -fasta_test BioAutoML/Case\ Studies/CS-I-A/E_coli/test/rRNA.fasta BioAutoML/Case\ Studies/CS-I-A/E_coli/test/sRNA.fasta -fasta_label_test rRNA sRNA -output test_directory

###################################################################################
###################################################################################
###################################################################################
###################################################################################

Train - BioAutoML/Case Studies/CS-I-A/E_coli/train/rRNA.fasta: Found File
Train - BioAutoML/Case Studies/CS-I-A/E_coli/train/sRNA.fasta: Found File
Test - BioAutoML/Case Studies/CS-I-A/E_coli/test/rRNA.fasta: Found File
Test - BioAutoML/Case Studies/CS-I-A/E_coli/test/sRNA.fasta: Found File
Extracting features with MathFeature...
Traceback (most recent call last):
  File "BioAutoML/BioAutoML-feature.py", line 414, in <module>
    fasta_test, fasta_label_test, features, foutput)
  File "BioAutoML/BioAutoML-feature.py", line 203, in feature_extraction
    train_size += len([1 for line in open(preprocessed_fasta) if line.startswith(">")])
FileNotFoundError: [Errno 2] No such file or directory: 'test_directory/feat_extraction/train/pre_rRNA.fasta'`

**Comment by Bonidia** [comment]
Dear jackievaleri,

We hope this email finds you well!

I'm glad to have helped you.

Try running it inside the package folder. For example:

cd BioAutoML

python BioAutoML-feature.py -fasta_train Case\ Studies/CS-I-A/E_coli/train/rRNA.fasta Case\ Studies/CS-I-A/E_coli/train/sRNA.fasta -fasta_label_train rRNA sRNA -fasta_test Case\ Studies/CS-I-A/E_coli/test/rRNA.fasta Case\ Studies/CS-I-A/E_coli/test/sRNA.fasta -fasta_label_test rRNA sRNA -output experimental/test_directory

Please feel free to reach out if you need anything.

Best regards,

Robson P Bonidia.

**Comment by gth-ai** [comment]
Dear Bonidia, 
I get the same error even though I'm in the right directory (BioAutoML).
